version: "3.2"

services:
  mongo:
    container_name: mongo
    image: mongo:4.0.23
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "password"

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    environment:
      REDIS_PASSWORD: "password"

  band-voting-service:
    container_name: band-voting-service
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./dist:/usr/local/app/dist
      - ./src:/usr/local/app/src
      - ./test:/usr/local/app/test
      - ./jest.config.js:/usr/local/app/jest.config.js
      - ./nest-cli.json:/usr/local/app/nest-cli.json
      - ./tsconfig.build.json:/usr/local/app/tsconfig.build.json
      - ./tsconfig.json:/usr/local/app/tsconfig.json
    ports:
      - 8080:8080
      - 9090:9090 # websocket
      - 9229:9229 # debug
    env_file:
      - .env
    depends_on: 
      - mongo
      - redis